# Generated by Django 4.0.3 on 2022-04-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
